baseURL = "http://localhost:1313"
languageCode = "es-ES"
title = "Blog de CorelTech"
theme = "cupper"
publishDir = "public"

[params]
  description = "Artículos técnicos sobre mantenimiento de hardware, software y redes."
  author = "CorelTech Servicios Técnicos"