baseURL = "https://coreltech-blog.vercel.app"
languageCode = "es-ES"
title = "Blog de CorelTech - Soluciones Técnicas"
theme = "basic"
publishDir = "public"

[params]
  description = "Artículos técnicos sobre mantenimiento de hardware, software y redes informáticas."
  author = "CorelTech Servicios Informáticos"
  keywords = ["mantenimiento", "hardware", "software", "redes", "soporte técnico", "CorelTech"]

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Artículos"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Hardware"
    url = "/categories/hardware/"
    parent = "Artículos"
    weight = 21

  [[menu.main]]
    name = "Software"
    url = "/categories/software/"
    parent = "Artículos"
    weight = 22

  [[menu.main]]
    name = "Redes"
    url = "/categories/redes/"
    parent = "Artículos"
    weight = 23

  [[menu.main]]
    name = "Sobre CorelTech"
    url = "/sobre-coreltech/"
    weight = 3

  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 4

 [outputs]
  home = ["HTML", "RSS"]
